---
- hosts: monitor
  roles:
    - role: ansible-integrated-elks
    - role: ansible-librenms

- hosts: clients
  roles:
    - role: snmp-debian
    - role: rsyslog-debian
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
      become: yes

    - name: Install tools.
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - git
        - logrotate
        - mc
        - nano
        - htop
...
