- name: test
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ groups['librenms-hosts'] }}"
  tags:
    - librenms-addhosts

- include: addhost.yml
  with_items:
    - "{{ groups['librenms-hosts'] }}"
  tags:
    - librenms-addhosts
